export const data = [
  {
    id: "MEMBER-001",
    Name: "Sarah Johnson",
    Role: "Premium Member",
    MembershipId: "GYM-2024-001",
    Email: "sarah.johnson@email.com",
    PHONE: "0512345678",
    ADDRESS: "123 Fitness St, Sports City",
    BIRTH: "January 15, 1990",
    GENDER: "Female",
    STATUS: "Active",
    MEMBERSHIP_STATUS: "Active",
    JOIN_DATE: "January 12, 2024",
    LAST_CHECKIN: "Today, 8:30 AM",
    TRAINER: "Mike Thompson",
    MEMBERSHIP_PLAN: "Premium Plus",
  },
  {
    id: "MEMBER-002",
    Name: "John Davis",
    Role: "Standard Member",
    MembershipId: "GYM-2024-002",
    Email: "john.davis@email.com",
    PHONE: "0512987654",
    ADDRESS: "456 Workout Ave, Gym District",
    BIRTH: "March 22, 1985",
    GENDER: "Male",
    STATUS: "Active",
    MEMBERSHIP_STATUS: "Frozen",
    JOIN_DATE: "February 5, 2024",
    LAST_CHECKIN: "Yesterday, 6:15 PM",
    TRAINER: "Lisa Rodriguez",
    MEMBERSHIP_PLAN: "Standard",
  },
  {
    id: "MEMBER-003",
    Name: "Emma Wilson",
    Role: "Trainer",
    MembershipId: "STAFF-001",
    Email: "emma.wilson@gym.com",
    PHONE: "0512777888",
    ADDRESS: "789 Health Rd, Fitness Zone",
    BIRTH: "August 30, 1992",
    GENDER: "Female",
    STATUS: "Active",
    MEMBERSHIP_STATUS: "Staff",
    JOIN_DATE: "December 1, 2023",
    LAST_CHECKIN: "Today, 7:00 AM",
    TRAINER: "N/A",
    MEMBERSHIP_PLAN: "Staff Membership",
  },
  {
    id: "MEMBER-004",
    Name: "Alex Chen",
    Role: "Premium Member",
    MembershipId: "GYM-2024-003",
    Email: "alex.chen@email.com",
    PHONE: "0512555666",
    ADDRESS: "321 Fitness Blvd, Health District",
    BIRTH: "November 8, 1988",
    GENDER: "Male",
    STATUS: "Inactive",
    MEMBERSHIP_STATUS: "Expired",
    JOIN_DATE: "March 10, 2024",
    LAST_CHECKIN: "2 weeks ago",
    TRAINER: "Mike Thompson",
    MEMBERSHIP_PLAN: "Premium",
  },
  {
    id: "MEMBER-005",
    Name: "Maria Garcia",
    Role: "Admin",
    MembershipId: "ADMIN-001",
    Email: "maria.garcia@gym.com",
    PHONE: "0512444333",
    ADDRESS: "654 Wellness St, Active Area",
    BIRTH: "July 14, 1980",
    GENDER: "Female",
    STATUS: "Active",
    MEMBERSHIP_STATUS: "Staff",
    JOIN_DATE: "January 1, 2023",
    LAST_CHECKIN: "Today, 9:00 AM",
    TRAINER: "N/A",
    MEMBERSHIP_PLAN: "Staff Membership",
  },
  {
    id: "MEMBER-006",
    Name: "David Kim",
    Role: "Standard Member",
    MembershipId: "GYM-2024-004",
    Email: "david.kim@email.com",
    PHONE: "0512333222",
    ADDRESS: "987 Exercise Rd, Fit Town",
    BIRTH: "April 5, 1995",
    GENDER: "Male",
    STATUS: "Active",
    MEMBERSHIP_STATUS: "Active",
    JOIN_DATE: "April 20, 2024",
    LAST_CHECKIN: "Today, 5:45 PM",
    TRAINER: "Lisa Rodriguez",
    MEMBERSHIP_PLAN: "Standard",
  },
];
