export const mealData = [
  {
    id: "MEAL-001",
    name: "Protein Power Breakfast Bowl",
    category: "breakfast",
    calories: 420,
    protein: 35,
    carbs: 45,
    fat: 12,
    status: "active",

    featured: true,
    ingredients: ["Oats", "Greek Yogurt", "Berries", "Protein Powder", "Nuts"],
  },
  {
    id: "MEAL-002",
    name: "Grilled Chicken Salad",
    category: "lunch",
    calories: 320,
    protein: 40,
    carbs: 15,
    fat: 8,
    status: "active",

    featured: false,
    ingredients: [
      "Chicken Breast",
      "Mixed Greens",
      "Cherry Tomatoes",
      "Cucumber",
      "Olive Oil",
    ],
  },
  {
    id: "MEAL-003",
    name: "Vegan Buddha Bowl",
    category: "dinner",
    calories: 380,
    protein: 22,
    carbs: 55,
    fat: 10,
    status: "active",
    featured: true,
    ingredients: ["Quinoa", "Sweet Potato", "Avocado", "Chickpeas", "Tahini"],
  },
  {
    id: "MEAL-004",
    name: "Post-Workout Shake",
    category: "snacks",
    calories: 280,
    protein: 30,
    carbs: 25,
    fat: 6,
    status: "active",
    featured: false,
    ingredients: [
      "Whey Protein",
      "Banana",
      "Almond Milk",
      "Peanut Butter",
      "Honey",
    ],
  },
  {
    id: "MEAL-005",
    name: "Mediterranean Wrap",
    category: "lunch",
    calories: 350,
    protein: 25,
    carbs: 40,
    fat: 9,
    status: "inactive",

    featured: false,
    ingredients: [
      "Whole Wheat Wrap",
      "Hummus",
      "Feta Cheese",
      "Olives",
      "Vegetables",
    ],
  },
  {
    id: "MEAL-006",
    name: "Energy Protein Bars",
    category: "snacks",
    calories: 220,
    protein: 15,
    carbs: 20,
    fat: 8,
    status: "active",
    featured: true,
    ingredients: ["Oats", "Protein Powder", "Dates", "Nuts", "Dark Chocolate"],
  },
  {
    id: "MEAL-007",
    name: "Salmon with Quinoa",
    category: "dinner",
    calories: 450,
    protein: 38,
    carbs: 35,
    fat: 18,
    status: "active",

    ingredients: ["Salmon Fillet", "Quinoa", "Asparagus", "Lemon", "Herbs"],
  },
  {
    id: "MEAL-008",
    name: "Overnight Oats",
    category: "breakfast",
    calories: 320,
    protein: 20,
    carbs: 45,
    fat: 7,
    status: "inactive",
    featured: false,
    ingredients: [
      "Rolled Oats",
      "Milk",
      "Chia Seeds",
      "Berries",
      "Maple Syrup",
    ],
  },
];
