export const trainingData = [
  {
    id: "TRN-001",
    name: "Strength Foundation Program",
    category: "strength",
    duration: 60,
    difficulty: "intermediate",
    calories: 420,
    status: "active",
    show: true,
  },
  {
    id: "TRN-002",
    name: "HIIT Fat Burner",
    category: "cardio",
    duration: 30,
    difficulty: "advanced",
    calories: 550,
    status: "active",
    show: false,
  },
  {
    id: "TRN-003",
    name: "Yoga for Flexibility",
    category: "flexibility",
    duration: 45,
    difficulty: "beginner",
    calories: 220,
    status: "active",
    show: true,
  },
  {
    id: "TRN-004",
    name: "Endurance Running",
    category: "endurance",
    duration: 75,
    difficulty: "intermediate",
    calories: 680,
    status: "active",
    show: false,
  },
  {
    id: "TRN-005",
    name: "Bodyweight Basics",
    category: "bodyweight",
    duration: 40,
    difficulty: "beginner",
    calories: 320,
    status: "inactive",
    show: true,
  },
  {
    id: "TRN-006",
    name: "Heavy Squats",
    category: "strength",
    duration: 90,
    difficulty: "advanced",
    calories: 480,
    status: "active",
    show: true,
  },
  {
    id: "TRN-007",
    name: "Heavy Squats",
    category: "endurance",
    count: 14,
    difficulty: "intermediate",
    calories: 520,
    status: "active",
    show: true,
  },
  {
    id: "TRN-008",
    name: "Heavy Squats",
    category: "flexibility",
    count: 10,
    difficulty: "beginner",
    calories: 280,
    status: "inactive",

    show: false,
  },
];
