export const trainingData = [
  {
    id: "TRN-001",
    name: "Strength Foundation Program",
    category: "strength",
    duration: 60,
    difficulty: "intermediate",
    calories: 420,
    status: "active",
    price: 49.99,
    featured: true,
    exercises: ["Squats", "Deadlifts", "Bench Press", "Overhead Press", "Rows"],
  },
  {
    id: "TRN-002",
    name: "HIIT Fat Burner",
    category: "cardio",
    duration: 30,
    difficulty: "advanced",
    calories: 550,
    status: "active",
    price: 29.99,
    featured: false,
    exercises: [
      "Burpees",
      "Mountain Climbers",
      "Jump Squats",
      "Push-ups",
      "Plank",
    ],
  },
  {
    id: "TRN-003",
    name: "Yoga for Flexibility",
    category: "flexibility",
    duration: 45,
    difficulty: "beginner",
    calories: 220,
    status: "active",
    price: 39.99,
    featured: true,
    exercises: [
      "Downward Dog",
      "Warrior Poses",
      "Tree Pose",
      "Cobra Stretch",
      "Child's Pose",
    ],
  },
  {
    id: "TRN-004",
    name: "Endurance Running",
    category: "endurance",
    duration: 75,
    difficulty: "intermediate",
    calories: 680,
    status: "active",
    price: 24.99,
    featured: false,
    exercises: [
      "Interval Running",
      "Hill Sprints",
      "Long Distance",
      "Fartlek",
      "Recovery Jog",
    ],
  },
  {
    id: "TRN-005",
    name: "Bodyweight Basics",
    category: "bodyweight",
    duration: 40,
    difficulty: "beginner",
    calories: 320,
    status: "inactive",
    price: 19.99,
    featured: false,
    exercises: [
      "Push-ups",
      "Bodyweight Squats",
      "Lunges",
      "Plank",
      "Glute Bridges",
    ],
  },
  {
    id: "TRN-006",
    name: "Powerlifting Program",
    category: "strength",
    duration: 90,
    difficulty: "advanced",
    calories: 480,
    status: "active",
    price: 59.99,
    featured: true,
    exercises: [
      "Heavy Squats",
      "Heavy Deadlifts",
      "Bench Press",
      "Accessory Lifts",
      "Mobility Work",
    ],
  },
  {
    id: "TRN-007",
    name: "Swimming Endurance",
    category: "endurance",
    duration: 60,
    difficulty: "intermediate",
    calories: 520,
    status: "active",
    price: 34.99,
    featured: true,
    exercises: [
      "Freestyle Drills",
      "Interval Swimming",
      "Kickboard Work",
      "Pull Buoy Sets",
      "Cool Down",
    ],
  },
  {
    id: "TRN-008",
    name: "Pilates Core",
    category: "flexibility",
    duration: 50,
    difficulty: "beginner",
    calories: 280,
    status: "inactive",
    price: 27.99,
    featured: false,
    exercises: [
      "Hundreds",
      "Roll Up",
      "Single Leg Circles",
      "Criss Cross",
      "Swan Dive",
    ],
  },
];
