export const blogData = [
  {
    id: "BLOG-001",
    title: "10 Best Exercises for Weight Loss",
    author: "Sarah Johnson",
    category: "fitness",
    status: "published",
    publishDate: "Jun 15, 2024",
    views: 12450,
    comments: 89,
    likes: 456,
    featured: true,
  },
  {
    id: "BLOG-002",
    title: "Nutrition Guide for Muscle Building",
    author: "Mike Thompson",
    category: "nutrition",
    status: "published",
    publishDate: "Jun 12, 2024",
    views: 8950,
    comments: 67,
    likes: 321,
    featured: false,
  },
  {
    id: "BLOG-003",
    title: "Morning Routine for Optimal Health",
    author: "Emma Wilson",
    category: "lifestyle",
    status: "draft",
    publishDate: "-",
    views: 0,
    comments: 0,
    likes: 0,
    featured: false,
  },
  {
    id: "BLOG-004",
    title: "Advanced Strength Training Techniques",
    author: "David Lee",
    category: "training",
    status: "published",
    publishDate: "Jun 8, 2024",
    views: 15600,
    comments: 124,
    likes: 589,
    featured: true,
  },
  {
    id: "BLOG-005",
    title: "Healthy Meal Prep Ideas",
    author: "Lisa Rodriguez",
    category: "nutrition",
    status: "published",
    publishDate: "Jun 5, 2024",
    views: 10200,
    comments: 78,
    likes: 412,
    featured: false,
  },
  {
    id: "BLOG-006",
    title: "Yoga for Stress Relief",
    author: "Maria Garcia",
    category: "lifestyle",
    status: "archived",
    publishDate: "May 28, 2024",
    views: 7800,
    comments: 45,
    likes: 234,
    featured: false,
  },
  {
    id: "BLOG-007",
    title: "Cardio vs Weight Training: What's Better?",
    author: "John Davis",
    category: "fitness",
    status: "published",
    publishDate: "May 22, 2024",
    views: 18900,
    comments: 156,
    likes: 678,
    featured: true,
  },
  {
    id: "BLOG-008",
    title: "Supplements Guide for Beginners",
    author: "Alex Chen",
    category: "nutrition",
    status: "draft",
    publishDate: "-",
    views: 0,
    comments: 0,
    likes: 0,
    featured: false,
  },
];
